language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: fgonzalezc-sesion6
  on: master
  skip_cleanup: true
  api_key:
    secure: DiwzSEqbkjZ5R5VPQ7dc5zvMVJZ1+7wDT1Ygj9LAEZYkbHd7Dh2KZcjTLTch6dfpgrXA+/eZa55DRVnlk1U9sB3k6ZvozyjGUTTREGLM+DYUOd0fIj3weDJYTWUS8fBszrExWcjA9s0ZDDyhs/UJRmE8SHNtVKTryA5MzcMU5asuMUhulqWb/YM+ShCFXX4L/lPDRR66eclA03mF+8ICcqohlr3Y5Ju94MRo+x7SzT4pmPIYKwN84I2gkR5PQRXUgL2Ng7uNSa1WUjOdE3+4Q8zmNuhIK+hqWwzDZ5efXS7SZk6Qjlnlf70e2cpBv8JR0b0AbWJeFspGEc1L3E6rG/xYgCnTxrbtPyh1+g9r0aqkTIIrUcMcjV4jnKj73QukvWFzHJ3J02vQIBNSMbDTKfTHJSGjU9wCfDX829wYXnwrHoB1lbBKMQudjDz4p8YXhmJ8vCceDxlLyeVZUcA+U0A/7UWk5+fgwwmy0emAE/h+7okAka6hrhSuUh9iwAt0+I8shfn6SFC0JGEat2Bz/HIttfJxKeunHDwNRpbCz0hlS7BKZv0VorHCUFgDofRKeK6sCHOQsosmnObV+Bw/BnOaL2E1n93xqcOht3L1ljHq58lgE3jTra3mgmuHIsKahIYWo9p9+RyzjFh1nKmjebyNzjk50xLvOXWp3V8hCc8=
